#include <iostream>
#include <cstdio>

// Include your custom headers if main needs to trigger the visualizer
// #include "ast.h"
// #include "visualizer.h" 

using namespace std;

// --- EXTERNAL FLEX/BISON VARIABLES ---
/*
 * yyparse: The main function generated by Bison. Calling this starts the 
 * parsing process (which in turn calls the lexer and your logic engine).
 * RETURNS: 0 if parsing/validation is successful, 1 if it fails.
 */
extern int yyparse();

/*
 * yyin: The file pointer that Flex reads from. By default, it reads from standard 
 * input, but we point it to our .solva file.
 */
extern FILE* yyin;

// --- OPTIONAL: GLOBAL AST ROOT ---
// If your parser builds an AST, you usually expose the root node here 
// so main() can pass it to the visualizer after parsing.
// extern ProgramNode* astRoot;


int main(int argc, char** argv) {
    /*
     * STEP 1: VALIDATE COMMAND LINE ARGUMENTS
     * WHAT IT DOES: Ensures the user actually provided a file to compile.
     * EXPECTS: argc to be at least 2 (e.g., `./solva input.solva`).
     */
    if (argc < 2) {
        cerr << "Usage: " << argv[0] << " <filename.solva>" << endl;
        return 1;
    }

    /*
     * STEP 2: FILE I/O
     * WHAT IT DOES: Opens the target .solva file and connects it to the Lexer.
     * EXPECTS: A valid file path.
     */
    FILE* inputFile = fopen(argv[1], "r");
    if (!inputFile) {
        cerr << "Error: Could not open file " << argv[1] << endl;
        return 1;
    }
    
    // Tell Flex to read from this file instead of the terminal
    yyin = inputFile;

    cout << "--- Starting SolvA Validation ---" << endl;

    /*
     * STEP 3: EXECUTE THE COMPILER PIPELINE
     * WHAT IT DOES: Runs the Lexer, Parser, and Logic Engine simultaneously (SDT).
     * EXPECTS: The rules defined in parser.y and logic_engine.cpp to handle the work.
     */
    int parseResult = yyparse();

    /*
     * STEP 4: HANDLE THE RESULTS
     * WHAT IT DOES: Provides final output and triggers AST visualization on success.
     */
    if (parseResult == 0) {
        cout << "\nSUCCESS: The provided CSP solution is syntactically and logically valid!" << endl;
        
        // TODO: Trigger visualization here.
        // Example: 
        // string dotCode = astRoot->toDot();
        // saveToFile("output.dot", dotCode);
        // cout << "Parse tree saved to output.dot" << endl;

    } else {
        // Note: The specific logic error message will have already been printed 
        // by the yyerror() function inside parser.y before reaching this point.
        cout << "\nFAILED: Validation aborted due to logic/syntax errors." << endl;
    }

    /*
     * STEP 5: CLEANUP
     * WHAT IT DOES: Closes file handles and frees memory to prevent leaks.
     */
    fclose(inputFile);
    
    // TODO: Clean up AST memory here if dynamically allocated
    // delete astRoot;

    return parseResult;
}